### ISSUE TITLE
Overly Complicated

### ISSUE THREAD

**Issue by Sc00bz** [sneves/avx512-utils#1]
You can replace the ternlog namespace in ternlog.hpp with:

```
namespace ternlog
{
    const int _a = 0xf0;
    const int _b = 0xcc;
    const int _c = 0xaa;
    const int _0 = 0x00;
    const int _1 = 0xff;

#if defined(__AVX512F__)
    static inline __m512i _mm512_boolean_epi32(int f, __m512i a, __m512i b, __m512i c)
    {
        return _mm512_ternarylogic_epi32(a, b, c, f & 0xff);
    }

    static inline __m512i _mm512_boolean_epi64(int f, __m512i a, __m512i b, __m512i c)
    {
        return _mm512_ternarylogic_epi64(a, b, c, f & 0xff);
    }
#endif
}
```

Then just use those constants:

```
using namespace ternlog;

__m512i F(__m512i a, __m512i b, __m512i c)
{
    return _mm512_boolean_epi64((_a&_b)|(~_a&_c), a, b, c);
}

__m512i G(__m512i a, __m512i b, __m512i c)
{
    return _mm512_boolean_epi64((_a&_c)|(_b&~_c), a, b, c);
}

// ...
```

I'm pretty sure _mm512_ternarylogic_epi\* will mask the int to the proper imm8. So you probably don't even need to do "f & 0xff". Also you should add the mask and maskz versions for both of them.

Hmm... I guess if you want to prevent people from doing non-bitwise operations with the constants then ignore this.

**Comment by sneves** [comment]
Neat, I didn't figure this out at the time. Otherwise I wouldn't have written this to begin with.

I would prefer to disallow non-boolean operations, but that's impossible without some extra complexity. I need to think about it.

**Comment by sneves** [comment]
I have now pushed a commit that adds masked operations and uses your simplification, while also prohibiting invalid operations on placeholder types. By the way, the `& 0xff` _is_ necessary.
